blank_issues_enabled: true
contact_links:
  - name: SurrealDB Documentation
    url: https://surrealdb.com/docs
    about: Official SurrealDB documentation
  - name: SurrealDB Discord
    url: https://discord.gg/surrealdb
    about: Community support
